
name: Testing

on:
  push:
    branches: master

jobs:
  tester:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Get and set NEW_VERSION
        run: |
          pip list

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get and set NEW_VERSION
        run: |
          pip list
          python -m unittest discover

































